### ISSUE TITLE
Add documentation about how to deploy with Vercel

### ISSUE THREAD

**Issue by abbyfischler** [hackclub/css-starter#4]
Update README.md file to include documentation about how to deploy the website with vercel

**Comment by abbyfischler** [comment]
https://github.com/abbyfischler/css-starter/pull/1

**Comment by exu3** [comment]
Vercel has a neat button to make this really easy!

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fhackclub%2Fcss-starter)


```
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fhackclub%2Fcss-starter)
```

and a Netlify one:

[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/hackclub/css-starter)

```
[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/hackclub/css-starter)
```

**Comment by abbyfischler** [comment]
https://github.com/hackclub/css-starter/pull/5

**Comment by jessicard** [comment]
Thanks @abbyfischler!
